version: '3.8'

services:
  nexia-exporter:
    image: ghcr.io/mattmendick/nexia-prometheus-exporter:latest
    container_name: nexia-prometheus-exporter
    environment:
      - NEXIA_USERNAME=${NEXIA_USERNAME}
      - NEXIA_PASSWORD=${NEXIA_PASSWORD}
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 